# Generated by Django 4.2.8 on 2023-12-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='waterCost',
            field=models.FloatField(default=0),
        ),
    ]
